"""
Runtime configuration for nixarr-py.

Configuration is loaded from a JSON file generated by NixOS.
The path can be overridden via the NIXARR_PY_CONFIG_PATH environment variable
for testing and development.
"""

from pathlib import Path
import os
import json
from functools import cache
from pydantic import BaseModel


DEFAULT_CONFIG_PATH = "/etc/nixarr/nixarr-py.json"
CONFIG_PATH: Path = Path(os.environ.get("NIXARR_PY_CONFIG_PATH", DEFAULT_CONFIG_PATH))


class SimpleService(BaseModel):
    base_url: str
    api_key_file: Path


class NixarrPyConfig(BaseModel):
    prowlarr: SimpleService | None = None
    radarr: SimpleService | None = None
    sonarr: SimpleService | None = None


@cache
def load_config() -> NixarrPyConfig:
    if not CONFIG_PATH.is_file():
        raise FileNotFoundError(f"Config file not found: {CONFIG_PATH}")

    with open(CONFIG_PATH, "r", encoding="utf-8") as file_handle:
        return NixarrPyConfig.model_validate(json.load(file_handle))


def get_simple_service_config(service: str) -> SimpleService:
    config = load_config()
    simple_service = getattr(config, service, None)
    assert simple_service is not None, (
        f"No configuration found for service '{service}' in {CONFIG_PATH}"
    )
    assert isinstance(simple_service, SimpleService), (
        f"{service} is not a simple service"
    )

    return simple_service