#+title: Secrets

Secrets are managed with age encryption and integrated with nix using the wonderful [[https://github.com/ryantm/agenix?tab=readme-ov-file#ageidentitypaths][agenix]] by ryantm.

* Editing Secrets

The list of secrets that can be created/edited is in [[file:secrets.nix]] and are populated with the following command.

#+begin_src shell
EDITOR=vim nix run github:ryantm/agenix -- -e cloudflare-api-env.age
#+end_src

if you change ssh keys and need to re-encrypt your age secrets the following command will re-encrypt all of theml

#+begin_src shell
EDITOR=vim nix run github:ryantm/agenix -- -r
#+end_src


* Authelia secrets

The majroity of authelia secrets are just 64 character long random strings that can be easily generated.

#+begin_src shell
nix run 'nixpkgs#authelia' -- crypto rand --length 64 --charset alphanumeric
#+end_src

a notable exception is `authelia-oicd-issuer.pem` which is actually an rsa keypair.

#+begin_src shell
nix run 'nixpkgs#authelia' -- crypto pair rsa generate
#+end_src

Apparently authelia does support DSA keys which could be interesting in future.

* Cloudflare

Any secret that ends in `env` such as `cloudflare-api-env.age` is actually an environment file not a raw secret.

#+begin_src txt
CLOUDFLARE_AUTH_TOKEN=<super secret token>
#+end_src
